# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

jobs:
  build:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        working-directory: client
    - name: Run CI
      run: npm ci
    - name: Clean cache
      run: npm cache clean --force
    - name: Run Install
      run: npm i
    - run: cd frontend
    - name: Run Install
      run: npm i
    - name: Run Build
      run: npm run build
      env:
        CI: false
    - run: cd ..
    - run: pm2 stop 0
    - name: Run Restart PM2
      run: pm2 start 0
    - run: pm2 save
    - name: Run Restart Nginx
      run: sudo service nginx restart

    